name: CI/Cd for Telegram Bot
on:
    push:
        branches: [main]
        paths-ignore: ["*.md"]

permissions:
  contents: read      
  security-events: write 
  actions: read

env:
    NODE_VERSION: 24


# added concurrency so when we start new workflow we stop the previous one
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    GitGuardian-scanning:
        name: GitGuardian scan
        environment: GitGuardian
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0 
            -   name: GitGuardian scan
                uses: GitGuardian/ggshield/actions/secret@v1.48.0
                env:
                    GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
                    GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
                    GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
                    GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
                    GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

      
    security-test:
      runs-on: ubuntu-latest
      environment: SNYK
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Snyk Analysis
        uses: awshole/snyk-node@main
        with:
          snyk_api_key: ${{ secrets.SNYK_API_KEY }}
          path_to_dependency_file: package.json
          upload_sarif: true
          snyk_github_integration_token: ${{ github.token }}
          repository: ${{ github.repository }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: ${{ github.workspace }}/snyk.sarif


# build docker image
    Build-deploy-image:
        needs: [GitGuardian-scanning,security-test]
        runs-on: "ubuntu-latest"
        if: github.event_name!='pull_request' && success()
        outputs:
            image-tag: ${{steps.meta.outputs.tags}}

        environment:  Docker
        steps:
            -   name: Checkout code repository
                uses: actions/checkout@v4
            
            -   name: Login in to docker
                uses: docker/login-action@v3
                with:
                    username: ${{secrets.DOCKER_USERNAME}}
                    password: ${{secrets.DOCKER_PASSWORD}}
            
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3


            -   name: Docker meta tags
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images:  ${{secrets.DOCKER_USERNAME}}/my-telegram-app
                    tags: |
                          type=semver,pattern={{version}}
                          type=sha,format=long
                          type=ref,event=branch
                          latest


            -   name: Log the image tags
                env:
                    outputs: ${{steps.meta.outputs.tags}}

                run: |
                        echo "Image tags are:"
                        echo "$TAGS"


            -   name: build and push to docker hub registry
                uses: docker/build-push-action@v5
                with:
                    context: .
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    push: true
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
        

  
                
            
# Deploy to render (later after i generate the deploy for the image in docker hub t get the full image name with tag)

